import enum
import types
from collections.abc import Mapping, Sequence
from typing import Annotated, Any, Self

import jax
import mlx
import numpy
from numpy.typing import NDArray

class DeviceError(Exception): ...
class CompileError(Exception): ...
class FunctionNotFoundError(CompileError): ...
class DispatchError(Exception): ...

def device_name() -> str: ...
def device_info() -> dict: ...
def supported_dtypes() -> str: ...
def library_cache_size() -> int: ...
def library_cache_limit() -> int: ...
def set_library_cache_limit(limit: int) -> None: ...
def clear_library_cache() -> None: ...

class Buffer:
    def __init__(
        self,
        array: Annotated[NDArray, dict(order="C", device="cpu", writable=False)],
        dtype: str | None = None,
    ) -> None: ...
    @staticmethod
    def zeros(shape: Sequence[int], dtype: str = "float32") -> Buffer: ...
    @staticmethod
    def empty(shape: Sequence[int], dtype: str = "float32") -> Buffer: ...
    def copy_from(
        self,
        array: Annotated[NDArray, dict(order="C", device="cpu", writable=False)],
        dtype: str | None = None,
    ) -> None: ...
    def to_numpy(self, dtype: str | None = None) -> NDArray: ...
    def to_jax(self) -> jax.Array: ...
    def to_mlx(self) -> mlx.core.array: ...
    def __dlpack__(self, **kwargs) -> Any: ...
    def __dlpack_device__(self) -> tuple: ...
    @property
    def shape(self) -> tuple: ...
    @property
    def dtype(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def __len__(self) -> int: ...

class MathMode(enum.StrEnum):
    """
    How much freedom the Metal compiler has to rewrite floating-point arithmetic.
    """

    SAFE = "safe"
    """
    IEEE semantics. Required for compensated summation and double-single arithmetic, whose error terms FAST is free to fold away.
    """

    RELAXED = "relaxed"
    """
    Permits reassociation like FAST (so it also deletes compensated arithmetic), but keeps infinities and NaNs well-defined instead of assuming they never occur.
    """

    FAST = "fast"
    """Metal's default: permits reassociation and flushes denormals."""

class Kernel:
    def __init__(
        self,
        msl_source: str,
        function_name: str,
        math_mode: MathMode = MathMode.FAST,
        defines: Mapping[str, str] = {},
        constants: dict = {},
    ) -> None: ...
    @property
    def function_name(self) -> str: ...
    @property
    def math_mode(self) -> MathMode: ...
    @property
    def defines(self) -> dict[str, str]: ...
    @property
    def constants(self) -> dict: ...
    @property
    def max_threads_per_threadgroup(self) -> int: ...
    @property
    def thread_execution_width(self) -> int: ...
    @property
    def static_threadgroup_memory_length(self) -> int: ...

def run(
    kernel: Kernel,
    grid: int | Sequence[int] | Buffer,
    threadgroup: int | Sequence[int] | None = None,
    buffers: Sequence[Buffer | tuple[Buffer, int]] = [],
    scalars: Sequence[numpy.ndarray | numpy.generic] = [],
    threadgroup_memory: Sequence[int] = [],
    indirect_offset: int = 0,
) -> None: ...

class Batch:
    def __init__(self, concurrent: bool = False) -> None: ...
    def add(
        self,
        kernel: Kernel,
        grid: int | Sequence[int] | Buffer,
        threadgroup: int | Sequence[int] | None = None,
        buffers: Sequence[Buffer | tuple[Buffer, int]] = [],
        scalars: Sequence[numpy.ndarray | numpy.generic] = [],
        threadgroup_memory: Sequence[int] = [],
        indirect_offset: int = 0,
    ) -> None: ...
    def barrier(self) -> None: ...
    def commit(self) -> None: ...
    def wait(self) -> None: ...
    @property
    def gpu_time(self) -> float | None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...
