import enum
import types
from collections.abc import Mapping, Sequence
from typing import Annotated, Self

import numpy
from numpy.typing import NDArray

class DeviceError(Exception): ...
class CompileError(Exception): ...
class FunctionNotFoundError(CompileError): ...
class DispatchError(Exception): ...

def device_name() -> str: ...
def device_info() -> dict: ...
def supported_dtypes() -> str: ...
def library_cache_size() -> int: ...
def library_cache_limit() -> int: ...
def set_library_cache_limit(limit: int) -> None: ...
def clear_library_cache() -> None: ...

class Buffer:
    def __init__(
        self,
        array: Annotated[NDArray, dict(order="C", device="cpu", writable=False)],
        dtype: str | None = None,
    ) -> None: ...
    @staticmethod
    def zeros(shape: Sequence[int], dtype: str = "float32") -> Buffer: ...
    def to_numpy(self, dtype: str | None = None) -> NDArray: ...
    @property
    def shape(self) -> tuple: ...
    @property
    def dtype(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def __len__(self) -> int: ...

class MathMode(enum.StrEnum):
    """
    How much freedom the Metal compiler has to rewrite floating-point arithmetic.
    """

    SAFE = "safe"
    """
    IEEE semantics. Required for compensated summation and double-single arithmetic, whose error terms FAST is free to fold away.
    """

    RELAXED = "relaxed"

    FAST = "fast"
    """Metal's default: permits reassociation and flushes denormals."""

class Kernel:
    def __init__(
        self,
        msl_source: str,
        function_name: str,
        math_mode: MathMode = MathMode.FAST,
        defines: Mapping[str, str] = {},
    ) -> None: ...
    @property
    def function_name(self) -> str: ...
    @property
    def math_mode(self) -> MathMode: ...
    @property
    def defines(self) -> dict[str, str]: ...
    @property
    def max_threads_per_threadgroup(self) -> int: ...
    @property
    def thread_execution_width(self) -> int: ...

def run(
    kernel: Kernel,
    grid: int | Sequence[int],
    threadgroup: int | Sequence[int] | None = None,
    buffers: Sequence[Buffer] = [],
    scalars: Sequence[numpy.ndarray | numpy.generic] = [],
    threadgroup_memory: Sequence[int] = [],
) -> None: ...

class Batch:
    def __init__(self) -> None: ...
    def add(
        self,
        kernel: Kernel,
        grid: int | Sequence[int],
        threadgroup: int | Sequence[int] | None = None,
        buffers: Sequence[Buffer] = [],
        scalars: Sequence[numpy.ndarray | numpy.generic] = [],
        threadgroup_memory: Sequence[int] = [],
    ) -> None: ...
    def wait(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...
